#ENC[AES256_GCM,data:x/FYtR2Qxi+c1xHrsb0oD6/R8S6Tk41fMuYnkIy+8Wd0IlcM/QjksLSH+7oZSi0djQkD5Z1tKdignwjcxDqU1cXn7Ynl8NE25Tbr2bk08wMj498XL3YgElCD6H3MG3/R21DprKp351Era7yVqK6rSEg2kLDQpnIGxxWTfPdOnCeB,iv:cDI3sZYxZne1KsOoHUgFciPu2qxISwtInwaQJz8NwjU=,tag:X/ObbD7d6rpthwq8ALSmDg==,type:comment]
#ENC[AES256_GCM,data:XfYvOfzF5tzvhtdBbvBvuz6ysiGTCLXZ8jDR/jLoWh0pAiEn0T8devBDdTv1zsEXNJYI7fCNYr0b8bIKRw==,iv:4DKGQJL7phL0i8pgN6hNsnRNAo+Otr0tCezguFLpBQY=,tag:09SeV8CPWP23Cfe9SOkpmg==,type:comment]
#ENC[AES256_GCM,data:dhjIZXyDNATempntpfoe4AXjdDlOg40D9ArTKt0/Y2QpBE2fYw==,iv:i7aszxOtZgSSRiztN1WbxMwwgH1I4egXR6yBSmLFzeE=,tag:vKt2O9QA9MWYWOMoN+WbSg==,type:comment]
#
#ENC[AES256_GCM,data:8yPi2cBa2fasXIzWx+hAJH0nu/ujlg1TI6oSLkzm3Gba7Izkv4U+k173CSAgtPXfCBmngKPFuDZkYz/TRwhCKKbzGKZ7mnk6KWnpnDtbXTYuUGPWCVp+JaumEAcuznPnFQ==,iv:wdYkAe4wSIZn6buSku/qTdPNGP//bUqq1Q68q9xExEE=,tag:M1nDlGDEIXrzILyVkJDOKw==,type:comment]
#ENC[AES256_GCM,data:XKIWKwJz9ul9F2etDo8oPfXvC86BXaGL2l7cD2253WySX2FkrwuIvjbui1thh7WKJHmtNBucdHbomCEyPaxZV/ftW2Zi/BNf7Qft6GWdpWIeQ1v1KxMMAIWQfgZp8P5IU1st8YDB3NY7QrW9z54DrWRsBlAUbYp40b0Wq75Rc8m+Ng==,iv:Hu666g1FmS7KRwKWw3uWGgRb9KhOyKFAZ3iFoyCi1e8=,tag:vSzmQkgmuGDpusSjIo+3Bg==,type:comment]
#ENC[AES256_GCM,data:I7PX6HOj3u+bYFRbtBEO2hcm/Md0WakBtcuNlynvbw==,iv:qyaokTMcYuDTIIkcNU3tWOqbPLI1vTbczX6HJRblT4I=,tag:7FQkpqrxmTrqfspeymGU2A==,type:comment]
secrets:
    DB_USER: ENC[AES256_GCM,data:Lbfv0g==,iv:QKyOZ+7TkenzMV0EGF+UmdQmbLRtFZHrjMGVsVeDTcg=,tag:U2vJ5nEw2qxHCdYiJl7/tQ==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:j6iGiQ==,iv:kRiM20flGEDt99mW53kgP8qGjtoEooZW57b6Hiyjo6A=,tag:1ufgsEqU8yAO1cWto6SIqA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVTGVVYTgxVU9ORlFaR0pJ
            VHpDU293TjdCdzFlZmNDTzJDeDVYRXh5UlFjCi9GWkltQW9jZWJUU3BFR2dyNEdr
            TnRrSk9zaGZRdURCV21kYythcmdlTzAKLS0tIHhzVEtlVnh0WDVYaGpSeG1DWm83
            UWQrQ0hwcFhvcURINFFVbitFV3hXejQKJP2TBVpvUA0f19Ock6Y40uyHOHTKLn/t
            jO5bi7pdRbIxTmfGhuvOclPmi9KnOXNl0tMiyvBRtZxPLVu5Nk1bYg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age144qpwrl0npcsv92ht4nsukcet7ydxyqseqj873v3gmavm3p54ausafz78e
    lastmodified: "2026-08-15T12:37:27Z"
    mac: ENC[AES256_GCM,data:Bnuc0RkseN081xR6ThOmGs68KGtqKLLHrFnNAFE87DaCX44pR/NvoLEWsyrx/X/AWJkT8AKqmOaRwgyxVP4ze1bFTFt4zKtlA4fEhs1OWy0bCYvfmDYzkof48USo5ymehKMlTeNKC/IP8k1Sp9kvAvqf4xjxJ9WrAnmdmMm9sEk=,iv:wa4A61V3WNbqR2YPcQPyXDkoKer+ysP4zMGNxC0HKWM=,tag:XRozTV6IDgqSRS6qEZTx5w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
