#ENC[AES256_GCM,data:CdMyCqOadMjXZ/wcv6SIS9HrPWMM39+wd31fw5Xup+VYMOVCq8COWh1kgyAJ75VHNGE1hdrFRIYeXs8zanOVSUUsFI2TtE03nyGFySJxUavqLKw3r1IjqhvarMC/op8x6ncApg/hvQvrnSrccJ/iKPz7rA9NTisCM3ph9wOy900=,iv:r/M0BKdTdQn5y9tn9SQ0iEafSX9VU85z7cOCaI9FeaA=,tag:n8A5lGPASYgXW3Lhfd9yYA==,type:comment]
#ENC[AES256_GCM,data:xTwhgGNRH/B0Swo/GT7WsQ6/ruRR+vpVMfdco2/a7TuyDID3l2kvLq/7kXA+P4At8YT5MZuYl6OY3n/ymL98Lq26pprkxB6o7YG5RTpK25rVqVDxN27NmeI4iAaZOCqMUCLGZgakiU39evNOdGAxb3zvH/yRkCBX,iv:qSstlRHMX5Q9O7hKIOnocniWcno75weSzaZv7DHwKgU=,tag:OOUfuPISzh8+/Vul0UsGQg==,type:comment]
#
#ENC[AES256_GCM,data:zHxVs4Y70l24NSEDSgF9fM8Nj19xqrdVbq1YVizuJ9G6GpbXOrlK+aLw9BoidJ8fe8DcdLRat9tkX38A8Py0SwSFsw==,iv:XAMQvBr1GTDKwUkStQD2jz7/QjS5+EY0h4Z4b+muOJ4=,tag:2FUvAO1TwnLFvrwwJ1CsBA==,type:comment]
#ENC[AES256_GCM,data:o87GPB4cgT9n8xaQ5Cxs2a1CLMteYVYtNcD2UpyXIAw7ovTxECooSQ==,iv:ZyCQFYh/vBowAu+nBdr9YcZcm71UkgU7je2GiZZ6CHU=,tag:z/6DhMMPYzzLkTaUE9jF6g==,type:comment]
#
#ENC[AES256_GCM,data:qkFRpL3DEGv6JqyYG1pAdsQIHH7emcQu2WJ0bvpTjUceaBPE3pbFeCS/vEk/V4hzLun7PMauunPLl5xrYloECd0MTPr/cBoqgq3tVSY4WdFtq6bDNPyIyGgUkB7n7PTCdyJrGyHbpqpKRaK+pszRC2yzOjqW,iv:kKZ8ntuCWYsx8Np4uAx5nrATHT6ZsFg9GkvHR+5a/I0=,tag:ymEwwbNzIlfjhTccA8BL0Q==,type:comment]
#ENC[AES256_GCM,data:8gu8E/DmVs1pxO3iE4dcrvFiYS0ZwU9M5RKacSIWoXfP/wQ59fmIiQ0BbFFXyCDdAngGc47y14MHrIyy9vztvFiPTL53mD0OZlI2XVtk8hgNPggrA50iB9N3Kn0cq9Lg8uwEAhxr8snDuPpl4NMWGOcGb4q5OtHpnTCAoJhAwGYT4Ij5IIsBgsSuqu2qO8d+ZXJDXe0=,iv:lyFkedDNylF5+iyIDqlu9rnBS6M7Sik9ihGhGDYRMRw=,tag:XrkwkmEZ9ewglMmAlqwbLQ==,type:comment]
secret:
    dbUser: ENC[AES256_GCM,data:kOwOyQ==,iv:vUt6/iYGjHLqYwcO9zA63TEmxhvzcqAd3/Ym8R1oFOo=,tag:ik/4qNkjPcGr8H7HtdvHbA==,type:str]
    dbPassword: ENC[AES256_GCM,data:pAuYaQ==,iv:DizUEJXptLF4dCacluHHa1SNV5Ug2m841MSNL8U1/bY=,tag:BLaR2POMBX5xhmFG324ehA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Znp6RHBoQ1g2TUhjRWR0
            dzkyNG5pUm1rUmJJeHFtZlFjenpPa21UTVNFCmduOTBXMEZHeEg1M05PZmVvZ0Jv
            NE1ZL29SeWh6YmJla3lXR2RhYWtDOGMKLS0tIElpc3JLWmJYMUhwQkJadmViTENC
            UFB4ZkthZ3l6TjJMcElFUmU4cG9uUUkKiBAiO8FG8XXpDVp21gS4JUBjzSJ4ylD8
            ii9p39Ri23KiLNKKq+7SagG6zGaPvEPpHTkyCsDuq3rsEw+B0nqU8g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age144qpwrl0npcsv92ht4nsukcet7ydxyqseqj873v3gmavm3p54ausafz78e
    lastmodified: "2026-08-15T12:37:04Z"
    mac: ENC[AES256_GCM,data:+YtJRCSpo9PDfs73iqHjmhQgatmHs2gSAinGFOpzOvhnnFeuCyF1cuCy8IxQ0WeK6irQNpSts/iSKEXR9dAbhAzWwO0AqwXuJt1jvip2l6KebmhrB4/sDNW0yGNOoU+nCzpzcJVzekoBoF303+u+mVBvu4ztKj63+fGRMGwGWas=,iv:Fttz7rfPdXOVSl/rY1gR6KB/D8wxIMyPCor9yqBGAls=,tag:VLeB3pswr88sIGLYJY87uA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
